### ISSUE TITLE
Error on "pip install DBOpt"

### ISSUE THREAD

**Issue by williambrown3** [Kaufman-Lab-Columbia/DBOpt#1]
When I attempt to install DBOpt using "pip install DBOpt", I receive an error saying:

"ERROR: Could not find a version that satisfies the requirement DBOpt (from versions: none)"
"ERROR: No matching distribution found for DBOpt"

I see that this is a brand new package and was wondering if you've made this publicly available for install yet?

Thank you!

**Comment by jhammer3018** [comment]
Should now work, let me know if you encounter any issues with the install.
